In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("cps_00008.csv")
df.head()

,YEAR,SERIAL,MONTH,CPSID,ASECFLAG,HFLAG,ASECWTH,REGION,PERNUM,CPSIDP,...,MARST,NATIVITY,HISPAN,OCC1990,IND1990,CLASSWKR,UHRSWORKT,EDUC,WKSWORK1,INCWAGE
0,2000,2,3,19981202520100,1,NaN,974.38,11,1,19981202520101,...,4,5,0,154,850,27,48,125,52,44600
1,2000,2,3,19981202520100,1,NaN,974.38,11,2,19981202520102,...,6,3,0,877,581,21,10,50,46,2000
2,2000,3,3,20000103263800,1,NaN,809.33,11,1,20000103263801,...,5,1,0,999,0,0,999,81,0,0
3,2000,3,3,20000103263800,1,NaN,809.33,11,2,20000103263802,...,6,1,0,505,612,21,43,81,48,12000
4,2000,4,3,20000102304500,1,NaN,946.16,11,1,20000102304501,...,4,1,0,274,651,21,39,73,52,20000

In [3]:
df['YEAR'].value_counts().sort_index()

YEAR
2000    133710
2001    218269
2002    217219
2003    216424
2004    213241
2005    210648
2006    208562
2007    206639
2008    206404
2009    207921
2010    209802
2011    204983
2012    201398
2013    202634
2014    199556
2015    199024
2016    185487
2017    185914
2018    180084
2019    180101
2020    157959
2022    152732
2023    146133
2024    144265
2025    142125
Name: count, dtype: int64

In [4]:
df.columns

Index(['YEAR', 'SERIAL', 'MONTH', 'CPSID', 'ASECFLAG', 'HFLAG', 'ASECWTH',
       'REGION', 'PERNUM', 'CPSIDP', 'CPSIDV', 'ASECWT', 'AGE', 'SEX', 'RACE',
       'MARST', 'NATIVITY', 'HISPAN', 'OCC1990', 'IND1990', 'CLASSWKR',
       'UHRSWORKT', 'EDUC', 'WKSWORK1', 'INCWAGE'],
      dtype='object')

In [5]:
#ENCODING

In [6]:
#1. Encode for sex

In [7]:
df['SEX'] = df['SEX'].replace(1, 'Male')
df['SEX'] = df['SEX'].replace(2, 'Female')
df['SEX'] = df['SEX'].replace(9, 'NIU')

In [8]:
df['RACE'].unique()

array([100, 200, 650, 300, 803, 804, 802, 651, 801, 652, 809, 805, 806,
       830, 807, 810, 820, 814, 811, 812, 808, 813, 816, 818, 817, 815,
       819], dtype=int64)

In [9]:
#Encode for Race

In [10]:
# Step 1: Map numeric race codes to analytic groups
race_map = {
    100: 'White',
    200: 'Black',
    300: 'Native',
    650: 'Asian',
    651: 'Asian',
    652: 'Asian'
}

df["RACE_REC"] = df["RACE"].map(race_map)

# Step 2: Everything else becomes "Other"
df["RACE_REC"] = df["RACE_REC"].fillna('Other')

# Step 3: Override with Hispanic ethnicity
df["RACE_ETH"] = np.where(df["HISPAN"] == 1, 'Hispanic', df["RACE_REC"])

In [11]:
df['RACE_ETH'].unique()

array(['White', 'Black', 'Asian', 'Native', 'Other'], dtype=object)

In [12]:
#Encoding for MARST

In [13]:
marst_map = {
    1: "Married, spouse present",
    2: "Married, spouse absent",
    3: "Separated",
    4: "Divorced",
    5: "Widowed",
    6: "Never married/single",
    7: "Widowed or Divorced",
    9: "NIU"
}

df['MARST'] = df['MARST'].replace(marst_map)

In [14]:
#Encoding for Nativity

In [15]:
nativity_map = {
    0: "Unknown",
    1: "Both parents native-born",
    2: "Father foreign, mother native",
    3: "Mother foreign, father native",
    4: "Both parents foreign",
    5: "Foreign born"
}

df['NATIVITY'] = df['NATIVITY'].replace(nativity_map)

In [16]:
#Encode for region:

In [17]:
region_map = {
    11: "New England Division",
    12: "Middle Atlantic Division",
    21: "East North Central Division",
    22: "West North Central Division",
    31: "South Atlantic Division",
    32: "East South Central Division",
    33: "West South Central Division",
    41: "Mountain Division",
    42: "Pacific Division",
    97: "State not identified"
}

df["REGION"] = df["REGION"].replace(region_map)

In [18]:
#Encoding for UHRSWORKT

In [19]:
df['UHRSWORKT'] = df['UHRSWORKT'].replace(997, "Hours vary")
df['UHRSWORKT'] = df['UHRSWORKT'].replace(999, "NIU")

In [20]:
#Encoding for

In [21]:
df.isna().sum()
df = df[df["AGE"].notna()]

In [22]:
#Encoding for Occupation

In [23]:
occ = pd.read_csv("codes1990.csv")

occ['code'] = occ['code'].astype(int)
df['OCC1990'] = df['OCC1990'].astype(int)
df['OCC1990'] = df['OCC1990'].replace(occ.set_index('code')['label'])

In [24]:
#Encoding for industry

In [25]:
ind = pd.read_csv("IND1990.csv")

ind['code'] = ind['code'].astype(int)
df['IND1990'] = df['IND1990'].astype(int)
df['IND1990'] = df['IND1990'].replace(ind.set_index('code')['label'])

In [26]:
#Encoding for class of worker

In [27]:
classwkr = pd.read_csv("CLASSWKR.csv")

classwkr['code'] = classwkr['code'].astype(int)
df['CLASSWKR'] = df['CLASSWKR'].astype(int)
df['CLASSWKR'] = df['CLASSWKR'].replace(classwkr.set_index('code')['label'])

In [28]:
#Encoding for education

In [29]:
educ = pd.read_csv("EDUC.csv")

educ['code'] = educ['code'].astype(int)
df['EDUC'] = df['EDUC'].astype(int)
df['EDUC'] = df['EDUC'].replace(educ.set_index('code')['label'])

In [30]:
#Encoding for Hispan

In [31]:
hispan_map = {
    0:   "Not Hispanic",
    100: "Mexican",
    102: "Mexican American",
    103: "Mexicano/Mexicana",
    104: "Chicano/Chicana",
    108: "Mexican (Mexicano)",
    109: "Mexicano/Chicano",
    200: "Puerto Rican",
    300: "Cuban",
    400: "Dominican",
    500: "Salvadoran",
    600: "Other Hispanic",
    610: "Central/South American",
    611: "Central American (excluding Salvadoran)",
    612: "South American",
    901: "Do not know",
    902: "N/A"
}

df['HISPAN'] = df['HISPAN'].replace(hispan_map)

In [32]:
df.head()

,YEAR,SERIAL,MONTH,CPSID,ASECFLAG,HFLAG,ASECWTH,REGION,PERNUM,CPSIDP,...,HISPAN,OCC1990,IND1990,CLASSWKR,UHRSWORKT,EDUC,WKSWORK1,INCWAGE,RACE_REC,RACE_ETH
0,2000,2,3,19981202520100,1,NaN,974.38,New England Division,1,19981202520101,...,Not Hispanic,Subject instructors (HS/college),Colleges and universities,State government employee,48,Doctorate degree,52,44600,White,White
1,2000,2,3,19981202520100,1,NaN,974.38,New England Division,2,19981202520102,...,Not Hispanic,Stock handlers,Hardware stores,"Wage/salary, private",10,Grade 10,46,2000,White,White
2,2000,3,3,20000103263800,1,NaN,809.33,New England Division,1,20000103263801,...,Not Hispanic,NIU,NIU,NIU,NIU,Some college but no degree,0,0,White,White
3,2000,3,3,20000103263800,1,NaN,809.33,New England Division,2,20000103263802,...,Not Hispanic,Automobile mechanics,Motor vehicle dealers,"Wage/salary, private",43,Some college but no degree,48,12000,White,White
4,2000,4,3,20000102304500,1,NaN,946.16,New England Division,1,20000102304501,...,Not Hispanic,"Salespersons, n.e.c.","Sporting goods, bicycles, and hobby stores","Wage/salary, private",39,High school diploma or equivalent,52,20000,White,White

In [33]:
#Creating a csv with all encoded information

In [34]:
df.to_csv("info.csv", index=False)

In [35]:
df.shape

(4731234, 27)