In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("info.csv")
df.head()

,YEAR,SERIAL,MONTH,CPSID,ASECFLAG,HFLAG,ASECWTH,REGION,PERNUM,CPSIDP,...,HISPAN,OCC1990,IND1990,CLASSWKR,UHRSWORKT,EDUC,WKSWORK1,INCWAGE,RACE_REC,RACE_ETH
0,2000,2,3,19981202520100,1,NaN,974.38,New England Division,1,19981202520101,...,Not Hispanic,Subject instructors (HS/college),Colleges and universities,State government employee,48,Doctorate degree,52,44600,White,White
1,2000,2,3,19981202520100,1,NaN,974.38,New England Division,2,19981202520102,...,Not Hispanic,Stock handlers,Hardware stores,"Wage/salary, private",10,Grade 10,46,2000,White,White
2,2000,3,3,20000103263800,1,NaN,809.33,New England Division,1,20000103263801,...,Not Hispanic,NIU,NIU,NIU,NIU,Some college but no degree,0,0,White,White
3,2000,3,3,20000103263800,1,NaN,809.33,New England Division,2,20000103263802,...,Not Hispanic,Automobile mechanics,Motor vehicle dealers,"Wage/salary, private",43,Some college but no degree,48,12000,White,White
4,2000,4,3,20000102304500,1,NaN,946.16,New England Division,1,20000102304501,...,Not Hispanic,"Salespersons, n.e.c.","Sporting goods, bicycles, and hobby stores","Wage/salary, private",39,High school diploma or equivalent,52,20000,White,White

In [3]:
df['RACE_ETH'].unique()

array(['White', 'Black', 'Asian', 'Native', 'Other'], dtype=object)

In [4]:
df['YEAR'].value_counts().sort_index()

YEAR
2000    133710
2001    218269
2002    217219
2003    216424
2004    213241
2005    210648
2006    208562
2007    206639
2008    206404
2009    207921
2010    209802
2011    204983
2012    201398
2013    202634
2014    199556
2015    199024
2016    185487
2017    185914
2018    180084
2019    180101
2020    157959
2022    152732
2023    146133
2024    144265
2025    142125
Name: count, dtype: int64

In [5]:
df.isna().sum()

YEAR               0
SERIAL             0
MONTH              0
CPSID              0
ASECFLAG           0
HFLAG        4531678
ASECWTH            0
REGION             0
PERNUM             0
CPSIDP             0
CPSIDV             0
ASECWT             0
AGE                0
SEX                0
RACE               0
MARST              0
NATIVITY           0
HISPAN          4725
OCC1990            0
IND1990            0
CLASSWKR           0
UHRSWORKT          0
EDUC               0
WKSWORK1           0
INCWAGE            0
RACE_REC           0
RACE_ETH           0
dtype: int64

In [6]:
df = df.drop(['HFLAG'], axis=1)

In [7]:
df.isna().sum()

YEAR            0
SERIAL          0
MONTH           0
CPSID           0
ASECFLAG        0
ASECWTH         0
REGION          0
PERNUM          0
CPSIDP          0
CPSIDV          0
ASECWT          0
AGE             0
SEX             0
RACE            0
MARST           0
NATIVITY        0
HISPAN       4725
OCC1990         0
IND1990         0
CLASSWKR        0
UHRSWORKT       0
EDUC            0
WKSWORK1        0
INCWAGE         0
RACE_REC        0
RACE_ETH        0
dtype: int64

In [8]:
df.shape

(4731234, 26)

In [9]:
df = df[df["HISPAN"].notna()]

In [10]:
df.columns

Index(['YEAR', 'SERIAL', 'MONTH', 'CPSID', 'ASECFLAG', 'ASECWTH', 'REGION',
       'PERNUM', 'CPSIDP', 'CPSIDV', 'ASECWT', 'AGE', 'SEX', 'RACE', 'MARST',
       'NATIVITY', 'HISPAN', 'OCC1990', 'IND1990', 'CLASSWKR', 'UHRSWORKT',
       'EDUC', 'WKSWORK1', 'INCWAGE', 'RACE_REC', 'RACE_ETH'],
      dtype='object')

In [11]:
df = df[df['UHRSWORKT'] != "NIU"]

In [12]:
(df == "NIU").sum()

YEAR         0
SERIAL       0
MONTH        0
CPSID        0
ASECFLAG     0
ASECWTH      0
REGION       0
PERNUM       0
CPSIDP       0
CPSIDV       0
ASECWT       0
AGE          0
SEX          0
RACE         0
MARST        0
NATIVITY     0
HISPAN       0
OCC1990      0
IND1990      0
CLASSWKR     0
UHRSWORKT    0
EDUC         0
WKSWORK1     0
INCWAGE      0
RACE_REC     0
RACE_ETH     0
dtype: int64

In [13]:
df.shape

(2190138, 26)

In [14]:
df['RACE'].unique()

array([100, 200, 650, 300, 803, 802, 651, 652, 801, 805, 804, 806, 830,
       810, 807, 809, 820, 811, 812, 808, 814, 813, 816, 818, 817, 815,
       819], dtype=int64)

In [15]:
df = df[(df['AGE'] >= 18) & (df['AGE'] <= 65)]

In [16]:
df.shape

(2065681, 26)

In [17]:
df = df[df['UHRSWORKT'] != "Hours vary"]

In [18]:
df['UHRSWORKT'] = pd.to_numeric(df['UHRSWORKT'], errors='coerce')

In [19]:
df.dtypes

YEAR           int64
SERIAL         int64
MONTH          int64
CPSID          int64
ASECFLAG       int64
ASECWTH      float64
REGION        object
PERNUM         int64
CPSIDP         int64
CPSIDV         int64
ASECWT       float64
AGE            int64
SEX           object
RACE           int64
MARST         object
NATIVITY      object
HISPAN        object
OCC1990       object
IND1990       object
CLASSWKR      object
UHRSWORKT      int64
EDUC          object
WKSWORK1       int64
INCWAGE        int64
RACE_REC      object
RACE_ETH      object
dtype: object

In [20]:
df['UHRSWORKT'].unique()

array([ 48,  43,  39,  45,  40,  50,  25,  60,  47,  38,  55,  32,  12,
        35,  15,  16,  20,   8,  13,  10,  30,  36,  58,  70,  44,   6,
        46,  26,  24,  57,  14,  42,  41,  54,  63,  37,  56,  80,  27,
         0,   4,  28,  85,  49,  61,  92,  98,  75,  33,  17,  18,  53,
        51,  62,  72,  65,  21,   9,  66,  22,  23,   2,  29,  34,   5,
        52,  68,  11,  93,   7,  99,  76,  90,  83,  67,  69, 100, 120,
        19,  31,  88,   3,  91,  96,  74,  59,  64,  84,   1,  77, 105,
       112,  73, 116,  78,  82, 124, 102,  95,  86,  94, 110, 111, 130,
        71, 125,  79, 198,  87,  89,  81, 101, 139, 140, 107,  97, 108,
       117, 104, 115, 109, 123, 113, 127, 168, 145, 114, 180, 132, 134,
       106, 144, 103, 126, 141, 129, 119, 133, 118, 179, 136, 148, 128,
       160, 150, 152, 137, 121, 138, 142, 147, 178, 135, 159, 131, 162,
       170, 188, 164, 169, 143, 122], dtype=int64)

In [21]:
df = df[(df['INCWAGE'] > 0) & (df['WKSWORK1'] > 0) & (df['UHRSWORKT'] > 0)]

In [22]:
df.shape

(1782076, 26)

In [23]:
df['EDUC'].unique()

array(['Doctorate degree', 'Some college but no degree',
       'High school diploma or equivalent', "Master's degree",
       "Bachelor's degree",
       "Associate's degree, occupational/vocational program", 'Grade 10',
       "Associate's degree, academic program", '12th grade, no diploma',
       'Professional school degree', 'Grade 9', 'Grade 11',
       'Grades 7 or 8', 'None or preschool', 'Grades 5 or 6',
       'Grades 1, 2, 3, or 4'], dtype=object)

In [24]:
ambiguous = [
    'Grades 1, 2, 3, or 4',
    'Grades 5 or 6',
    'Grades 7 or 8',
    'Some college but no degree',
    'None or preschool'
]
df = df[df['EDUC'].isin(ambiguous) == False]

In [25]:
df.shape

(1402419, 26)

In [26]:
df['EDUC'].unique()

array(['Doctorate degree', 'High school diploma or equivalent',
       "Master's degree", "Bachelor's degree",
       "Associate's degree, occupational/vocational program", 'Grade 10',
       "Associate's degree, academic program", '12th grade, no diploma',
       'Professional school degree', 'Grade 9', 'Grade 11'], dtype=object)

In [27]:
education_years = {
    'Grade 9': 9,
    'Grade 10': 10,
    'Grade 11': 11,

    '12th grade, no diploma': 12,
    'High school diploma or equivalent': 12,

    "Associate's degree, occupational/vocational program": 14,
    "Associate's degree, academic program": 14,

    "Bachelor's degree": 16,

    "Master's degree": 18,

    'Professional school degree': 19,
    'Doctorate degree': 21
}
df['EDUCYRS'] = df['EDUC'].map(education_years)

In [28]:
df['YEAR'].value_counts().sort_index()

YEAR
2000    39595
2001    64241
2002    62751
2003    62185
2004    61576
2005    60666
2006    60802
2007    61750
2008    61474
2009    59603
2010    59561
2011    58501
2012    57925
2013    58535
2014    58537
2015    58426
2016    54835
2017    55992
2018    54775
2019    55595
2020    48402
2022    47722
2023    46395
2024    46503
2025    46072
Name: count, dtype: int64

In [29]:
df["HISPAN"].unique()

array(['Not Hispanic', 'Puerto Rican', 'Other Hispanic',
       'Mexican American', 'Central/South American', 'Do not know',
       'Cuban', 'Mexican (Mexicano)', 'Chicano/Chicana', 'Mexican',
       'Dominican', 'South American',
       'Central American (excluding Salvadoran)', 'Salvadoran'],
      dtype=object)

In [30]:
#BINARY ENCODING FOR HISPAN

In [31]:
# First replace "Not Hispanic" with 0
df['HISPAN'] = df['HISPAN'].replace({'Not Hispanic': 0})

# Now convert everything else into 1 using np.where
df['HISPAN'] = np.where(df['HISPAN'] == 0, 0, 1).astype(int)

In [32]:
#BINARY ENCODING FOR CLASSWKR

In [33]:
# Replace all government categories with 1
df['CLASSWKR'] = df['CLASSWKR'].replace({
    'Federal government employee': 1,
    'State government employee': 1,
    'Local government employee': 1
})

# All remaining categories become 0
df['CLASSWKR'] = np.where(df['CLASSWKR'] == 1, 1, 0).astype(int)

In [34]:
# Make a panel of counts for every column by YEAR
panel_counts = df.groupby("YEAR").count().reset_index()

# Optional: save to CSV
panel_counts.to_csv("yearly_panel_counts.csv", index=False)

panel_counts

,YEAR,SERIAL,MONTH,CPSID,ASECFLAG,ASECWTH,REGION,PERNUM,CPSIDP,CPSIDV,...,OCC1990,IND1990,CLASSWKR,UHRSWORKT,EDUC,WKSWORK1,INCWAGE,RACE_REC,RACE_ETH,EDUCYRS
0,2000,39595,39595,39595,39595,39595,39595,39595,39595,39595,...,39595,39595,39595,39595,39595,39595,39595,39595,39595,39595
1,2001,64241,64241,64241,64241,64241,64241,64241,64241,64241,...,64241,64241,64241,64241,64241,64241,64241,64241,64241,64241
2,2002,62751,62751,62751,62751,62751,62751,62751,62751,62751,...,62751,62751,62751,62751,62751,62751,62751,62751,62751,62751
3,2003,62185,62185,62185,62185,62185,62185,62185,62185,62185,...,62185,62185,62185,62185,62185,62185,62185,62185,62185,62185
4,2004,61576,61576,61576,61576,61576,61576,61576,61576,61576,...,61576,61576,61576,61576,61576,61576,61576,61576,61576,61576
5,2005,60666,60666,60666,60666,60666,60666,60666,60666,60666,...,60666,60666,60666,60666,60666,60666,60666,60666,60666,60666
6,2006,60802,60802,60802,60802,60802,60802,60802,60802,60802,...,60802,60802,60802,60802,60802,60802,60802,60802,60802,60802
7,2007,61750,61750,61750,61750,61750,61750,61750,61750,61750,...,61750,61750,61750,61750,61750,61750,61750,61750,61750,61750
8,2008,61474,61474,61474,61474,61474,61474,61474,61474,61474,...,61474,61474,61474,61474,61474,61474,61474,61474,61474,61474
9,2009,59603,59603,59603,59603,59603,59603,59603,59603,59603,...,59603,59603,59603,59603,59603,59603,59603,59603,59603,59603
10,2010,59561,59561,59561,59561,59561,59561,59561,59561,59561,...,59561,59561,59561,59561,59561,59561,59561,59561,59561,59561
11,2011,58501,58501,58501,58501,58501,58501,58501,58501,58501,...,58501,58501,58501,58501,58501,58501,58501,58501,58501,58501
12,2012,57925,57925,57925,57925,57925,57925,57925,57925,57925,...,57925,57925,57925,57925,57925,57925,57925,57925,57925,57925
13,2013,58535,58535,58535,58535,58535,58535,58535,58535,58535,...,58535,58535,58535,58535,58535,58535,58535,58535,58535,58535
14,2014,58537,58537,58537,58537,58537,58537,58537,58537,58537,...,58537,58537,58537,58537,58537,58537,58537,58537,58537,58537
15,2015,58426,58426,58426,58426,58426,58426,58426,58426,58426,...,58426,58426,58426,58426,58426,58426,58426,58426,58426,58426
16,2016,54835,54835,54835,54835,54835,54835,54835,54835,54835,...,54835,54835,54835,54835,54835,54835,54835,54835,54835,54835
17,2017,55992,55992,55992,55992,55992,55992,55992,55992,55992,...,55992,55992,55992,55992,55992,55992,55992,55992,55992,55992
18,2018,54775,54775,54775,54775,54775,54775,54775,54775,54775,...,54775,54775,54775,54775,54775,54775,54775,54775,54775,54775
19,2019,55595,55595,55595,55595,55595,55595,55595,55595,55595,...,55595,55595,55595,55595,55595,55595,55595,55595,55595,55595
20,2020,48402,48402,48402,48402,48402,48402,48402,48402,48402,...,48402,48402,48402,48402,48402,48402,48402,48402,48402,48402
21,2022,47722,47722,47722,47722,47722,47722,47722,47722,47722,...,47722,47722,47722,47722,47722,47722,47722,47722,47722,47722
22,2023,46395,46395,46395,46395,46395,46395,46395,46395,46395,...,46395,46395,46395,46395,46395,46395,46395,46395,46395,46395
23,2024,46503,46503,46503,46503,46503,46503,46503,46503,46503,...,46503,46503,46503,46503,46503,46503,46503,46503,46503,46503
24,2025,46072,46072,46072,46072,46072,46072,46072,46072,46072,...,46072,46072,46072,46072,46072,46072,46072,46072,46072,46072

In [35]:
df.dtypes

YEAR           int64
SERIAL         int64
MONTH          int64
CPSID          int64
ASECFLAG       int64
ASECWTH      float64
REGION        object
PERNUM         int64
CPSIDP         int64
CPSIDV         int64
ASECWT       float64
AGE            int64
SEX           object
RACE           int64
MARST         object
NATIVITY      object
HISPAN         int32
OCC1990       object
IND1990       object
CLASSWKR       int32
UHRSWORKT      int64
EDUC          object
WKSWORK1       int64
INCWAGE        int64
RACE_REC      object
RACE_ETH      object
EDUCYRS        int64
dtype: object

In [36]:
df['RACE_ETH'].unique()

array(['White', 'Black', 'Asian', 'Native', 'Other'], dtype=object)

In [37]:
df.to_csv("democleaned.csv", index=False)